name: Run Jest Tests

on:
  push:
    branches:
      - main
      # - staging

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.13.1
          cache: 'pnpm' # enable pnpm lockfile caching

      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.15.4
          run_install: false

      - name: Install dependencies
        run: pnpm install

      - name: Run Jest tests
        run: pnpm test --runInBand --verbose
